language: php

php:
    - '5.6'
    - '7.0'

before_script:
    mkdir tests/data & composer install -n

script:
    - phpunit --configuration tests/phpunit.xml --coverage-clover build/logs/clover.xml tests
    - CODECLIMATE_REPO_TOKEN=ea35a3cdfec0b65d58fe2c9808a95936252826f9aaf567c5bdb4a3c9b251abdc
    - ./vendor/bin/test-reporter

deploy:
  provider: heroku
  api_key:
    secure: F7LgJU1kZGZo+IEuCUzqR0su4g+5ceXPfbhr1j4L2PW2itrAKl6a9bY4QgDuAsEAlzqqvXTkw7euvzvFlSkTa+iuyUcc+cYRInbLTFpaU0um7znqs7I+/8K9e32BZFn/QjodAG+orqDZ4VmSEylCsDHHK4jhawo4myRO8OtLHDLtZAnZs+bA6R5A4fJvbVVEBDDKcf+ejTKK85p3XA3Cy3xvF1gJ6JIpxEDuyAQQjhFC9CmQ4qC7jUtlq1X+UFTCzFGceo4Cy7zSiOZDLhkf9E2wTYKbZB/qDy2i4aLn8ZCJzT1wdeKFhqN+aF82qpGA287TTdtBUQNJFGynwQ9JwhfaG/8FS/h/tHK90kDslu0Tj3q9Xv32Pn+LH2PjidQ+qKS9U/4RqyGUPSe+eGMXB8ACFmx7lQAke6lFZ25Tcn5w+g7M33uLjpinq4gnpSm6dgsfy47Rhg/ghZ5mjQNVbMitaCBzj1bGL/ei+BScsfTBueBX8rG4PAQyTTZ/SRG4zKb3JEVgQdGmhsn0UABxQdRMmRsIuHpFCx/Klf+Sg5jKTAFpUFGpsRIqqpjOQEwPjdMGl7qMP3E/N7Fcx1nqZsRX0Gda8KkF0WZ1PpPrzL1Q0qaQsnR4xBqeIJipHu6rUK6JSzxIZ21zmaFdlpwqn2iP3otmmknCa8C1koNHahQ=
  app: ticketbox-php-test
  on:
    repo: ssigg/ticketbox-server-php

addons:
    code_climate:
        repo_token: ea35a3cdfec0b65d58fe2c9808a95936252826f9aaf567c5bdb4a3c9b251abdc