language: php
php:
- '5.6'
- '7.0'
before_script: mkdir tests/data & composer install -n
script:
- phpunit --configuration tests/phpunit.xml --coverage-clover build/logs/clover.xml tests
  tests
- CODECLIMATE_REPO_TOKEN=ea35a3cdfec0b65d58fe2c9808a95936252826f9aaf567c5bdb4a3c9b251abdc
- "./vendor/bin/test-reporter"
deploy:
  provider: heroku
  api_key:
    secure: R9jCnMNGAhjEbTgYwYPhZDn+kinPH2LsrdKsFI4DHEpyrwJJpiFpSPRquPi06jzyuscfP/gVS3cayP4cgjTQ1MthubBIcF41nckeKJZos57m8fQSFOSivib86+IOF/99ADVNOWufN2m6zuJ2B2yNDTCQOsJVDaN7+8RgdlgKIFqQ/Vq2jq6PqpdDAm97hx8PvC3mBrVj9kmvYd/2VjunZFGcFkgCXui7RXWb+HghbmN2rL9U2pFo0NfgjPXlWkoFzgWRj6vm647KjQH/0jLlRz28mCEed9RMmnT+Kp7cwnoBQy1BpZm4A8ap8TPy6wb/Jz+RkSlU+DxTDZ7xYj/ulkcUvMI7kcDa4fwN0gEqug5s8n2a/r2P6PY8LCPNp/Vke9KMZHdgtcpUszimyNwFnh3wTG/keODax2xgbMTStV20jKptdf2HH2bDZKfdDo2DV6f0n55mhb256uAMhettcuNq+3UCQJU3aNkV9W0DYJUQ20vLEHq7VZd829QTrdrKDI44c2Jijtj1pTog13Bw+sD4hcHjLFLAf9rCT65KEknAAWephgQRMROwFQEyc5fgb829jWCboUoGBt7cAkCUCyHixhYhjDetd49Vu7IgXOMOqUfHMeGSqiKsvrje7KcpeMVxP/zSyMm1J9MpNuBEHhqS5bAkD2Eqzk//ffKrEnc=
  app: ticketbox-php-test
  on:
    repo: ssigg/ticketbox-server-php
    branch: single-api
addons:
  code_climate:
    repo_token: ea35a3cdfec0b65d58fe2c9808a95936252826f9aaf567c5bdb4a3c9b251abdc
