language: php

php:
    - 5.6
    - 7.1
    - 7.2
    - 7.3

before_script:
    mkdir tests/data & composer install -n

script:
    - ./vendor/bin/phpunit --configuration tests/phpunit.xml --coverage-clover build/logs/clover.xml tests
    - CODECLIMATE_REPO_TOKEN=ea35a3cdfec0b65d58fe2c9808a95936252826f9aaf567c5bdb4a3c9b251abdc
    - ./vendor/bin/test-reporter

addons:
    code_climate:
        repo_token: ea35a3cdfec0b65d58fe2c9808a95936252826f9aaf567c5bdb4a3c9b251abdc